### PR TITLE
Explaining why other formats aren't suitable

### PR DESCRIPTION
**Pull request by martinthomson**

### CODE REVIEW

**Comment by martinthomson** [comment]
Oops, forgot to add refs, don't merge yet.

**Comment by martinthomson** [comment]
OK.

**Comment by martinthomson** [comment]
@msporny, I don't know what alignment means here, unless you mean that you would like to remove "algorithm".

**Comment by msporny** [comment]
@martinthomson I mean more do we use "keyid" or "keyId" (note the capitalized I in the latter form). Your comment did make me go back and look at the Content-Encoding: aesgcm-128 part and made me wonder if we wouldn't want to go the other way. Add "algorithm" to the spec, so you'd have something like this, instead:
```
Content-Encoding: encrypted, gzip
Encryption: keyid="http://example.org/bob/keys/123";
            algorithm="aesgcm-128";
            nonce="XZwpw6o37R-6qoZjw6KwAw"
```

I realize that doing that might be a bit of an abuse of the Content-Encoding field, but having something that's a bit more flexible would probably be a good thing.

**Comment by martinthomson** [comment]
@msporny, that sort of flexibility is a strict non-goal for us here.

**Comment by msporny** [comment]
@martinthomson Why? Is this explained somewhere?

**Comment by martinthomson** [comment]
I'll explain here.  Mark and I have both had a lot of experience with developing or maintaining protocol frameworks with multiple extension points.  Those are significantly harder to get right than you initially think, every time.  The biggest costs usually only surface several years after the spec is complete, usually in the form of interop failure as a result of divergent interpretations of some spec ambiguity.

Unless you have a strong need for it, don't provide extensibility.  Use existing, well-tested extension points.  A high-level discriminator - such as our "aesgcm-128" C-E tag - uses the existing Content-Encoding extension scheme.  A replacement can use the same point easily.  It's also a pattern that has worked very well elsewhere.  Other than your basic extension point, design the minimum possible thing that could possibly work.

This is exactly the same design philosophy that has been applied in HTTP/2, though for that we had to design a new extension point to get what we wanted.  And ALPN was NOT easy to do, nor are we yet entirely certain it is correct or error free.

So, when we want to do an AEAD based on ChaCha20 and Poly1305, we will define a new content encoding, and maybe the pieces that work from this one, if there are any.

**Comment by msporny** [comment]
@martinthomson thanks for taking the time to explain. What you're saying makes sense in that we've kinda-sorta taken that approach wrt. the digital signature "algorithm agility" stuff in the Linked Data Signatures work (https://web-payments.org/specs/source/ld-signatures/#message-signature-algorithm). That is, we try to just bundle all the crypto settings into a single identifier (GraphSignature2012) vs. enabling a ton of variability.

I'll think about what you say above and try and apply the thinking to the Signing HTTP Messages spec wrt. removing 'algorithm'. Thanks again for the explanation. :)

**Pull request merged**
